########### Les différents dictionnaires d'ids ###########
item_to_id = {
    "unknown_item": 0,
    None : 0,
    "None": 0,
    '': 0,
    "choiceband": 1,
    "choicescarf": 2,
    "choicespecs": 3,
    "expertbelt": 4,
    "focussash": 5,
    "leftovers": 6,
    "lifeorb": 7,
    "lumberry": 8,
    "powerherb": 9,
    "salacberry": 10,
    "sitrusberry": 11,
    "blacksludge": 12,
    "thickclub": 13,       # os de Ossatueur (Marowak)
    "lightball": 14,       # objet de Pikachu
    "flameplate": 15, 
    "fistplate": 16,
    "earthplate": 17, 
    "stoneplate": 18, 
    "zapplate": 19,
    "meadowplate": 20, 
    "icicleplate": 21, 
    "toxicplate": 22, 
    "mindplate": 23, 
    "insectplate": 24,
    "spookyplate": 25, 
    "dracoplate": 26, 
    "dreadplate": 27, 
    "ironplate": 28, 
    "skyplate": 29,
    "splashplate": 30,
    "damprock": 31,
    "blackglasses": 32,
    "silkscarf": 33,
    "toxicorb": 34,
    "griseousorb" : 35,
    "stick": 36,
    "lustrousorb" : 37,
    "souldew" : 38,
    "chestoberry": 39,
    "custapberry": 40
}

ability_to_id = {
    "adaptability": 1,
    "aftermath": 2,
    "airlock": 3,
    "anticipation": 4,
    "arenatrap": 5,
    "baddreams": 6,
    "battlearmor": 7,
    "blaze": 8,
    "chlorophyll": 9,
    "clearbody": 10,
    "cloudnine": 11,
    "colorchange": 12,
    "compoundeyes": 13,
    "cutecharm": 14,
    "download": 15,
    "drizzle": 16,
    "drought": 17,
    "dryskin": 18,
    "earlybird": 19,
    "filter": 20,
    "flamebody": 21,
    "flashfire": 22,
    "flowergift": 23,
    "forecast": 24,
    "forewarn": 25,
    "frisk": 26,
    "gluttony": 27,
    "guts": 28,
    "hugepower": 29,
    "hydration": 30,
    "hypercutter": 31,
    "immunity": 32,
    "innerfocus": 33,
    "insomnia": 34,
    "intimidate": 35,
    "ironfist": 36,
    "keeneye": 37,
    "leafguard": 38,
    "levitate": 39,
    "limber": 40,
    "liquidooze": 41,
    "magicguard": 42,
    "magnetpull": 43,
    "marvelscale": 44,
    "minus": 45,
    "moldbreaker": 46,
    "motordrive": 47,
    "multitype": 48,
    "naturalcure": 49,
    "noguard": 50,
    "overgrow": 51,
    "owntempo": 52,
    "pickup": 53,
    "plus": 54,
    "poisonheal": 55,
    "poisonpoint": 56,
    "pressure": 57,
    "purepower": 58,
    "quickfeet": 59,
    "rockhead": 60,
    "roughskin": 61,
    "runaway": 62,
    "sandstream": 63,
    "sandveil": 64,
    "scrappy": 65,
    "serenegrace": 66,
    "shadowtag": 67,
    "shedskin": 68,
    "shellarmor": 69,
    "shielddust": 70,
    "simple": 71,
    "skilllink": 72,
    "slowstart": 73,
    "sniper": 74,
    "snowcloak": 75,
    "snowwarning": 76,
    "solidrock": 77,
    "soundproof": 78,
    "speedboost": 79,
    "static": 80,
    "steadfast": 81,
    "stickyhold": 82,
    "sturdy": 83,
    "suctioncups": 84,
    "superluck": 85,
    "swarm": 86,
    "swiftswim": 87,
    "synchronize": 88,
    "tangledfeet": 89,
    "technician": 90,
    "thickfat": 91,
    "tintedlens": 92,
    "torrent": 93,
    "trace": 94,
    "truant": 95,
    "unburden": 96,
    "vitalspirit": 97,
    "voltabsorb": 98,
    "waterabsorb": 99,
    "waterveil": 100,
    "whitesmoke": 101,
    "wonderguard": 102
}

types = [
    "bug", "dark", "dragon", "electric", "fighting", "fire", "flying", "ghost",
    "grass", "ground", "ice", "normal", "poison", "psychic", "rock", "steel",
    "water"
]

from poke_env.environment.weather import Weather
from poke_env.environment.side_condition import SideCondition
weather_to_id = {
    None: 0,  # Pour les cas où il n'y a pas de météo
    Weather.UNKNOWN: 0,
    Weather.SUNNYDAY: 1,
    Weather.RAINDANCE: 2,
    Weather.SANDSTORM: 3,
    Weather.HAIL: 4
}
side_condition_to_id = {
    SideCondition.STEALTH_ROCK: 0,
    SideCondition.SPIKES: 1,
    SideCondition.TOXIC_SPIKES: 3,
    SideCondition.REFLECT: 5,
    SideCondition.LIGHT_SCREEN: 7,
    SideCondition.TAILWIND: 9,
    SideCondition.STICKY_WEB: 11  # (pas présent en Gen 4, mais au cas où tu fais d'autres formats)
}